String normalizeText(String text) {
  return text
      .toLowerCase()
      .replaceAll('á', 'a')
      .replaceAll('ä', 'a')
      .replaceAll('č', 'c')
      .replaceAll('ď', 'd')
      .replaceAll('é', 'e')
      .replaceAll('ě', 'e')
      .replaceAll('í', 'i')
      .replaceAll('ľ', 'l')
      .replaceAll('ĺ', 'l')
      .replaceAll('ň', 'n')
      .replaceAll('ó', 'o')
      .replaceAll('ô', 'o')
      .replaceAll('ŕ', 'r')
      .replaceAll('š', 's')
      .replaceAll('ť', 't')
      .replaceAll('ú', 'u')
      .replaceAll('ů', 'u')
      .replaceAll('ý', 'y')
      .replaceAll('ž', 'z')
      .replaceAll('Á', 'a')
      .replaceAll('Ä', 'a')
      .replaceAll('Č', 'c')
      .replaceAll('Ď', 'd')
      .replaceAll('É', 'e')
      .replaceAll('Ě', 'e')
      .replaceAll('Í', 'i')
      .replaceAll('Ľ', 'l')
      .replaceAll('Ĺ', 'l')
      .replaceAll('Ň', 'n')
      .replaceAll('Ó', 'o')
      .replaceAll('Ô', 'o')
      .replaceAll('Ŕ', 'r')
      .replaceAll('Š', 's')
      .replaceAll('Ť', 't')
      .replaceAll('Ú', 'u')
      .replaceAll('Ů', 'u')
      .replaceAll('Ý', 'y')
      .replaceAll('Ž', 'z');
}

String stripHtmlTags(String html) {
  String plainText = html
      .replaceAll(RegExp(r'<sup[^>]*>.*?</sup>'), '')
      .replaceAll(RegExp(r'<p[^>]*>'), '')
      .replaceAll('</p>', '\n')
      .replaceAll('<br>', '\n')
      .replaceAll('<br/>', '\n')
      .replaceAll('<br />', '\n')
      .replaceAll(RegExp(r'<[^>]*>'), '')
      .replaceAll('&nbsp;', ' ')
      .replaceAll('&#039;', "'")
      .replaceAll('&apos;', "'")
      .replaceAll('&amp;', '&')
      .replaceAll('&lt;', '<')
      .replaceAll('&gt;', '>')
      .replaceAll('&quot;', '"')
      .replaceAll('&#39;', "'")
      .replaceAll(RegExp(r'\n+'), '\n')
      .trim();

  return plainText;
}
